export const dummyData = [
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '85',
    cashOut: '',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '85',
    cashOut: '',
  },
  {
    category: 'cat 1',
    paymentMode: 'pay',
    remark: 'some dummy text',
    cashIn: '85',
    cashOut: '',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '',
    cashOut: '36',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: '',
    cashIn: '',
    cashOut: '36',
  },
  {
    category: 'cat 1',
    remark: 'some dummy text',
    cashIn: '',
    cashOut: '36',
  },
  {
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '',
    cashOut: '75',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '',
    cashOut: '75',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text dskns  k  sdss  k dssd c sd csd mcsc k',
    cashIn: '',
    cashOut: '75',
  },
  {
    category: 'cat 1',
    paymentMode: 'Pay1',
    remark: 'some dummy text',
    cashIn: '',
    cashOut: '75',
  },
]
